### ISSUE TITLE
Solr async is losing data ?

### ISSUE THREAD

**Issue by HakanKaraoglu** [SolrNet/SolrNet#554]
Hi,

I'm using the solr add method for an asynchronous application (RabbitMQ). However, synchronous data indexing was causing too much data to accumulate in the queues. Later I saw Solr's asynchronous method support and wanted to test it, but I ran into a problem like this.

When I want to index 10k data in a parallel loop, it indexes the data incompletely, sometimes up to 500 or 600 or 700 data is not indexed. I tried the same example 3 times and each time I saw different results. The experiment I made is very simple as follows, but I do not understand what the problem is. Has anyone encountered such a problem before?

```
var solService = serviceProvider.GetService<ISolrIndexService<SolrDocument>>();
 
 Parallel.For(0, 10000, count =>
            {
                Console.WriteLine($"value of count = {count}, thread = {Thread.CurrentThread.ManagedThreadId}");

                var solrDocument = new SolrDocument()
                {
                    Id = Guid.NewGuid().ToString(),
                    CollectType = "FeedType",
                    ContentType = "ReTweet",
                    Country = "Turkey",
                    CreateTime = DateTime.Now,
                    FeedDate = DateTime.Now,
                    FeedLevel = 3,                  
                    KeywordText = new string[2] { "ser", "can" },
                    Klout = 3                   
                };
                solService.AddAsync(solrDocument);
            });
```

Note: The same example will give the correct result when run as sync.

**Comment by mausch** [comment]
Hi Hakan, I see an issue in that code: it's missing an `await` in the call to `AddAsync`.
And because this is an async function, you can't really use `Parallel.For` (see e.g. https://stackoverflow.com/a/19292500 ).
What I use in cases like this is https://github.com/Dasync/AsyncEnumerable#example-3-async-parallel-for-each

**Comment by pschwaller74** [comment]
I had a similar problem using AddRangeAsync() (instead of adding one document at a time, I create chunks of them before sending them to Solr index) and I fixed it using .Wait() inside Parallel.ForEach() loop. This will ensure that the Parallel.ForEach loop is waiting for an acknowledge from Solr server that the documents are indexed before the same parallel thread is serving Solr with a next document chunk (or at least I think it is). Also I suggest you set MaxDegreeOfParallelism to a reasonable value. You are "bombarding" Solr server and it's not able to cope with the amount of requests at the same time.

**Comment by HakanKaraoglu** [comment]
Hi @mausch 

I changed the code as you say.But it got worse, it processed 2k data from 10k data and then got the error I mentioned below.

```
var solService = serviceProvider.GetService<ISolrIndexService<SolrDocument>>();
 
 Parallel.For(0, 10000, count =>
            {
                Console.WriteLine($"value of count = {count}, thread = {Thread.CurrentThread.ManagedThreadId}");

                var solrDocument = new SolrDocument()
                {
                    Id = Guid.NewGuid().ToString(),
                    CollectType = "FeedType",
                    ContentType = "ReTweet",
                    Country = "Turkey",
                    CreateTime = DateTime.Now,
                    FeedDate = DateTime.Now,
                    FeedLevel = 3,                  
                    KeywordText = new string[2] { "ser", "can" },
                    Klout = 3                   
                };
               await solService.AddAsync(solrDocument);
            });
```

```
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__54.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrNet.Impl.AutoSolrConnection.<PostStreamAsStreamAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrNet.Impl.AutoSolrConnection.<PostAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrNet.Impl.LowLevelSolrServer.<SendAndParseHeaderAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrPerformanceTest.SolrIndexService`2.<AddAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrPerformanceTest.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

  This exception was originally thrown at this call stack:
    [External Code]
```

**Comment by HakanKaraoglu** [comment]
Hi @pschwaller74 

I tried as you said but unfortunately the result is as follows.

 ```
var solService = serviceProvider.GetService<ISolrIndexService<SolrDocument>>(); 

Parallel.For(0, 10000, new ParallelOptions { MaxDegreeOfParallelism = 4 }, async count =>
            {
                Console.WriteLine($"value of count = {count}, thread = {Thread.CurrentThread.ManagedThreadId}");

                var solrDocument = new SolrDocument()
                {
                    Id = Guid.NewGuid().ToString(),
                    CollectType = "FeedType",
                    ContentType = "ReTweet",
                    Country = "Turkey",
                    CreateTime = DateTime.Now,
                    FeedDate = DateTime.Now,
                    FeedLevel = 3,                  
                    KeywordText = new string[2] { "ser", "can" },
                    Klout = 3                   
                };
               await solService.AddAsync(solrDocument);
            });
```
```
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=The operation was canceled.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnectionPool.<SendWithNtConnectionAuthAsync>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.DecompressionHandler.<SendAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrNet.Impl.AutoSolrConnection.<PostStreamAsStreamAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrNet.Impl.AutoSolrConnection.<PostAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrNet.Impl.LowLevelSolrServer.<SendAndParseHeaderAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrPerformanceTest.SolrIndexService`2.<AddAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SolrPerformanceTest.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Inner Exception 1:
IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

Inner Exception 2:
SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
```

**Comment by HakanKaraoglu** [comment]
@mausch I may have expressed it wrong, I would like to state again. obviously i tried to imitate rabbitmq consumer with parallel for. As you know, it works asynchronously in consumers. The code block I expect to run is actually like this

```
var _currentFeed = await _unitOfWork.FeedRepository.FindByAsync(feedId);

                    if (_currentFeed != null && !_currentFeed.IsSpam && _currentFeed.IsActive)
                    {
                        var currentFeedDetail = await _unitOfWork.FeedDetailRepository.GetFeedDetailByFeedAsync(_currentFeed);

                        if (currentFeedDetail != null)
                        {
                            var solrDocument = new SolrDocument();

                            solrDocument.Id = _currentFeed.Id.ToString();
                            solrDocument.Title = !string.IsNullOrEmpty(_currentFeed.Title) ? _currentFeed.Title : "";
                            solrDocument.Body = !string.IsNullOrEmpty(currentFeedDetail.Body) ? currentFeedDetail.Body : "";
                            _currentFeed.IsIndexSolr = _solrOperations.AddUpdate(solrDocument);
                            var state = await _unitOfWork.FeedRepository.UpdateAsync(_currentFeed);
                        }
                    }
```

I wanted to do such a test before I wonder if the same problem may be there.

**Comment by mausch** [comment]
@HakanKaraoglu From my perspective, all I see in this github issue for now is code that uses .NET parallel/async incorrectly. I still don't see any issues with SolrNet itself.
I'm sorry but I won't do consultancy here. Please post a repro for an issue with SolrNet, otherwise I'll just have to close this.

**Comment by HakanKaraoglu** [comment]
@mausch  Thanks for your support, I'm closing the form.
